before_script:
  - npm install -g gulp
script: gulp

language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
  - 7
matrix:
  allow_failures:
    - node_js: 7
os:
  - linux
  - centos
  - macosx
  - windows
before_install:
  - npm install
  - npm i gulp -g
  - sleep 3
script: npm test
# after_script:
#   - nsp check
#   - gulp test:coverage
#   - node_modules/.bin/lcov-result-merger 'coverage/**/lcov.info' | node_modules/coveralls/bin/coveralls.js
# notifications:
#   webhooks:
#     urls:
#       - $GITTER_IM_URL
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
